#!/bin/bash

func ()
{
    local var1
    var1=$(($1 + $2))

    echo "var1 in func = $var1"

    if [[ $var1 -ge 7 ]]; then
	return
    else
	return $var1
    fi
}

var1="10"
echo "var1 = $var1"
func $1 $2
echo "func = $?"
echo "var1 = $var1"
