#!/bin/bash

#
# Operacoes sobre Strings
#

echo "Operacoes sobre Strings"
echo

a=1234zipper43231
echo "O stringa que se estah manipulando eh \"$a\"."

# length: comprimento de string
b=`expr length $a`
echo "Comprimento de \"$a\" is $b."

# index: posicao do primeiro caracter no substring 
# que coincide com um caracter em um string
b=`expr index $a 23`
echo "Posicao do primeiro \"2\" em \"$a\" eh \"$b\"."

# substr: extrai substring, iniciando com posicao e comprimento especificados
b=`expr substr $a 2 6`
echo "Substring de \"$a\", iniciando na posicao 2,\
e com 6 caracteres de comprimento eh \"$b\"."


#  O comportamento default da operacao 'match' eh procurar no *** inicio *** do string
#  pelo padrao indicado na Expressao Regular
#
b=`expr match "$a" '[0-9]*'`               #  contagem numerica
echo "Numero de digitos no inicio de \"$a\" eh $b."
b=`expr match "$a" '\([0-9]*\)'`           #  Note-se que os parênteses são precedidos de \
#                   ==      ==             
echo "Os digitos no inicio de \"$a\" sao \"$b\"."

echo
echo "Fim de Operacoes sobre Strings"
echo
